### ISSUE TITLE
Ricorsione

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ricorsione#2]
guarda il file fattoriale e dimmi se ok

**Comment by lucifero55** [comment]
Tutto chiaro.

**Comment by FabioZTessitore** [comment]
allora vediamo come faresti la somma di due interi mediante una  funzione ricorsiva (ipotizzando il secondo addendo non negativo)

**Comment by lucifero55** [comment]
Non ne sono capace

**Comment by lucifero55** [comment]
Somma (int a, int b){

If (b >= 0) return a+b;

else Somma(int a, int b+1);

Una cosa del genere? :/

**Comment by FabioZTessitore** [comment]
non proprio.

per arrivare a programmare una funzione ricorsiva devi immaginare un modo per spezzare il tuo problema in qualcosa di più semplice.
per esempio nel caso del fattoriale n! = n * (n-1)! stai dicendo: "il fattoriale di n non lo so calcolare, però se riesco a calcolare il fattoriale di (n-1) (problema minore) allora mi basta fare il prodotto con n"

Ovviamente ad un certo punto il problema non si può ridurre più e quindi ottieni il caso base. Sempre nel fattoriale ottieni il caso base quando n vale 0 e in quel caso non rimandi la risoluzione ad un problema minore ma restituisci il risulatato che è 1.

**Comment by lucifero55** [comment]
Questo lo avevo capito, ma nel caso della somma come avrei dovuto fare? :/

**Comment by FabioZTessitore** [comment]
non vuoi pensarci un po'?

suggerimento: data la somma a + b, devi trovare un problema "più semplice" da risolvere

**Comment by lucifero55** [comment]
"return a+b" è la cosa più semplice che riesco a pensare :/

**Comment by FabioZTessitore** [comment]
dato un numero a, sommarlo a b è un'operazione complessa haha nel senso che puoi immaginarla come composizione di operazioni più semplici

**Comment by lucifero55** [comment]
Dovete illuminarmi voi T.T

**Comment by FabioZTessitore** [comment]
hai un computer che sa solo aggiungere 1

**Comment by lucifero55** [comment]
If b==1 Return 1

Return somma(a,b-1)+a


Qualcosa del tipo? T.T

**Comment by FabioZTessitore** [comment]
stai cominciando a capire ma sei ancora lontano.
ricorda che l'unica operazione che sai fare è la somma con 1

**Comment by lucifero55** [comment]
if b==1 return 1
if a==1 return 1

return 1+somma(a,b-1)  + 1+somma(a-1,b)?

**Comment by FabioZTessitore** [comment]
mi dice cha hai scritto qualcosa ma non vedo il post

**Comment by lucifero55** [comment]
perchè l'ho tolto subito xD

**Comment by lucifero55** [comment]
sono tornato a casa. Sto provando creando un programma con somma() per vedere se riesco a farlo funzionare

**Comment by FabioZTessitore** [comment]
ok, have fun

**Comment by lucifero55** [comment]
Se la funzione accetta un solo parametro riesco, altrimenti non riesco T.T

**Comment by lucifero55** [comment]
Posso avere un esempio di una funzione ricorsiva con 2 variabili diversa da Somma()?
Potrebbe darmi un grande aiuto.

**Comment by FabioZTessitore** [comment]
Fammi vedere dove sei arrivato. Questo è il primo esercizio con la ricorsione, non è detto che devi riuscire a farlo da solo

**Comment by lucifero55** [comment]
Riesco a generare lo stesso valore di 'a' o di 'b', ma non so come sommarci l'altro.

**Comment by FabioZTessitore** [comment]
Questa è la tua funzione somma:
```C
int somma(int a, int b)
{
    if (a==1) return 1;
    return 1 + somma(a-1, b);
}```

La chiamata ricorsiva va bene (a parte il fatto che bisognava scalare b perché per ipotesi b è sempre non negativo; invece di a non sei sicuro).

Il caso base invece no. Prima di tutto non capisco perché ti fermi a 1. Quando a è 1 puoi ancora fare una chiamata ricorsiva. Quindi la condizione diventa `if (a==0)`.
Poi devi chiederti "se viene chiamata `somma(0, b)` cosa deve restituire la funzione?"

Ps. ricorda di invertire a e b

**Comment by lucifero55** [comment]
perchè, come ho caricato ora, non ritorna il reale valore di b.

**Comment by FabioZTessitore** [comment]
non ho capito che vuoi dire ...

cmq riguardo al codice ti rifaccio la domanda:
"se viene chiamata somma(a, 0) cosa deve restituire la funzione?"

**Comment by lucifero55** [comment]
a

**Comment by FabioZTessitore** [comment]
appunto, invece restituisci un 1 che non significa niente

**Comment by lucifero55** [comment]
"hai un computer che sa solo aggiungere 1" 
Pensavo di dover usare solo 1 T.T

**Comment by FabioZTessitore** [comment]
aggiungere solo 1. Ritornare quello che vuoi haha

**Comment by FabioZTessitore** [comment]
ok va bene.

ps ricordati di mettere il .gitignore che come vedi carichi sempre l'eseguibile
