### ISSUE TITLE
Cifre

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ricorsione#3]
stampa le cifre di un numero al contrario mediante una funzione ricorsiva

**Comment by lucifero55** [comment]
a=54
Inverti(int a);
printf("%d",a);

uscita:45

Così?

**Comment by FabioZTessitore** [comment]
si senza la printf (ci pensa la funzione inverti a stampare

**Comment by lucifero55** [comment]
Per il .gitignore bastava scrivere il nome dell'eseguibile?

**Comment by FabioZTessitore** [comment]
yes, sir

**Comment by FabioZTessitore** [comment]
ho fatto piccole modifiche (aggiunta del gitignore, aggiunta di un prompt, modifica del nome della funzione per l'inversione delle cifre, aggiustamenti alla formattazione) quindi fai un pull.

ps. il programma funziona con 54, ma non con 1234
evidentemente l'algoritmo non è corretto

**Comment by FabioZTessitore** [comment]
nessuna idea?

**Comment by lucifero55** [comment]
non fa più neanche quello che faceva prima :/
Come mai?

**Comment by lucifero55** [comment]
Per ora no

**Comment by FabioZTessitore** [comment]
se togli \n dalla scanf andrà meglio ... ovviamente se inserisci 45 ti risponderà 9 perché l'algoritmo è sbagliato.

ricorda: quando lavori con le funzioni ricorsive devi spezzare il problema in due parti. Una facile che fai subito e l'altra di difficoltà inferiore al problema originario ma dello stesso tipo.
Es. Nel caso della somma a+b spezzavi il problema in una parte facile (somma 1) e in una parte un po' piu' semplice del problema originario ma dello stesso tipo somma(a, b-1) ottenendo:
1 + somma(a, b-1)

In questo caso qual è l'operazione che puoi fare subito?
Qual è l'operazione dello stesso tipo del prob iniziale ma "un po' piu' semplice"?

**Comment by FabioZTessitore** [comment]
cominciano a comparire degli operatori che ti servono a risolvere il problema. per resto è da buttare.
prova a chiamarla stampa_in_ordine_inverso() magari ti viene qualche idea migliore

**Comment by lucifero55** [comment]
Consigli su cosa dovrebbe ritornare la funzione nel caso si verificasse il caso base?

**Comment by FabioZTessitore** [comment]
se l'ho chiamata stampa_in_ordine_inverso() secondo te che farà?

**Comment by lucifero55** [comment]
mi verrebbe in mente di 
1 prendere il numero e stampare il risultato di %10 'stampa Num%10'
2 dividere il numero per 10 'Num/10'
3 ripetere il primo passaggio

**Comment by FabioZTessitore** [comment]
perfetto

**Comment by lucifero55** [comment]
Come diventa codice? T.T

**Comment by FabioZTessitore** [comment]
haha

la parte facile del problema, quella che si fa subito, l'hai individuata al punto 1.
la parte 2 invece diventa un problema dello stesso tipo di quello iniziale ma un po' piu' facile

esempio:
input 123
1) stampa 3
2) stampa 12 in ordine inverso

**Comment by lucifero55** [comment]
1 if() return a%10;?

**Comment by FabioZTessitore** [comment]
stampa stampa stampa

**Comment by lucifero55** [comment]
1 if() printf("%d",a%10);

**Comment by FabioZTessitore** [comment]
eh

**Comment by lucifero55** [comment]
Quindi la funzione diventa void

**Comment by FabioZTessitore** [comment]
mi pare ovvio

**Comment by lucifero55** [comment]
Non riesco a capire come T.T

**Comment by lucifero55** [comment]
Qual'è la mentalità che devo avere riguardo la creazione di una funzione ricorsiva?

Il ragionamento di prima andava bene per un ciclo, e le fasi rispecchiavano a pieno il codice.
Qui invece è più complesso :/

**Comment by FabioZTessitore** [comment]
Sto cercando di spiegartelo da una settimana ... se solo leggessi quello
che scrivo!

Cmq ripeto: una operazione veloce da fare subito, un problema più semplice
di quello originale ma dello stesso tipo (ricorsione)

Immagina di dover invertire 1234. Risultato 4321. Lo ottieni così:
1) stampa 4
2) inverti(123) (è lo stesso prob di invertire 1234, ma più semplice perché
il numero è più corto) quindi ricorsione

Il venerdì 9 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Mi dica che va bene T.T

**Comment by FabioZTessitore** [comment]
va benino. ti ho inviato la mia versione per confronto.
dovresti notare che fare `if (a<10) ... a%10` non ha molto senso perché se `a<10` allora è una cifra e l'operazione è inutile

**Comment by lucifero55** [comment]
Giusto. 
Quindi anche nelle funzioni void puoi si può utilizzare return.

**Comment by FabioZTessitore** [comment]
Si ma senza ritornare niente. È un modo per evitare una if

Il sabato 10 settembre 2016, lucifero55 <notifications@github.com> ha
scritto:
