### ISSUE TITLE
La torre di Hanoi

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ricorsione#5]
![es5_39_parte_i](https://cloud.githubusercontent.com/assets/3002194/18410018/cb46bc30-7756-11e6-8165-43386e67565d.png)
![es5_39_parte_ii](https://cloud.githubusercontent.com/assets/3002194/18410022/d6be2fa8-7756-11e6-9c09-073aacb5d29e.png)
![es5_39_parte_iii](https://cloud.githubusercontent.com/assets/3002194/18410028/e0839802-7756-11e6-831d-bcf81f5e9689.png)

**Comment by lucifero55** [comment]
Questo gioco lo facevo sempre in prima media xD usavo le matite in ordine di grandezza xD
L'insegnante mi vide muovere le matite sul banco rimasi imbarazzatissimo hahaha.

**Comment by FabioZTessitore** [comment]
sei completamente fuori strada. rileggi bene il testo, ti dice esattamente cosa fare

**Comment by lucifero55** [comment]
cosa si intende con 4 parametri?

**Comment by FabioZTessitore** [comment]
non sai cosa sono i parametri di una funzione?
ah già dimenticavo che le funzioni non le usi e non hai internet

**Comment by lucifero55** [comment]
quindi esce qualcosa del tipo void TorreD(int a,int b,int c,int d);

**Comment by FabioZTessitore** [comment]
si

**Comment by lucifero55** [comment]
Il caso base è ok?

**Comment by FabioZTessitore** [comment]
perfetto

**Comment by FabioZTessitore** [comment]
ci siamo però per completezza nella parte else, la seconda istruzione non dovrebbe essere print, ma una chiamata ricorsiva
