### ISSUE TITLE
Ricorsione in coda

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ricorsione#6]
Ricapitoliamo cosa succede quando viene chiamata una 
funzione ricorsiva, ad esempio fattoriale(5):

fat(5) -> 5 * fat(4)

La funzione non può effettuare il calcolo finché non viene calcolato fat(4).

A sua volta fat(4) -> 4 * fat(3)
e così via.

In altre parole bisogna aspettare che si arrivi alla funzione "più interna" e poi procedere a ritroso per chiudere le funzioni (vedi figura).

## Ricorsione in coda

Quando la chiamata ricorsiva è l'ultima istruzione di una funzione si ottiene la ricorsione in coda.

In questi casi il compilatore puo' eseguire un'ottimizzazione e trasformare la ricorsione in una iterazione.

**Comment by lucifero55** [comment]
Chiaro
